---
# Default variables for paru-aur-helper role

# Paru git repository
paru_repo_url: https://aur.archlinux.org/paru.git

# Temporary build directory
paru_build_dir: /tmp/paru

# Add any role-specific defaults here
